### ISSUE TITLE
Texture Block not "load" for items in hand/inventory

### ISSUE THREAD

**Issue by choukpop** [arketec/Custom-Machinery#1]
[kubejs.zip](https://github.com/user-attachments/files/16125033/kubejs.zip)
kubejs folder to test

There is a bug where the texture on the block does not stay in the hand/inventory

![image](https://github.com/arketec/Custom-Machinery/assets/127648242/21808dc7-60ff-47e8-84c7-49e92cd1c0ac)

discord print channel #updates for 1.21 by frinn
![image](https://github.com/arketec/Custom-Machinery/assets/127648242/002255c0-04bd-41c2-8341-890a839540c3)

**Comment by arketec** [comment]
the 1.21 change are quite extensive, so back porting would be a pretty big change. I implemented a work-around for it tho, so it works now in the latest version

https://github.com/arketec/Custom-Machinery/commit/fa5a13a34def8365a979db4d105c212489dc4f02

**Comment by arketec** [comment]
closing as fixed for now, if there are other issues, or something else goes wrong, feel free to submit another issue
