### ISSUE TITLE
Not saving in correct instance modpack folder (/cm create)

### ISSUE THREAD

**Issue by choukpop** [arketec/Custom-Machinery#2]
I don't know if it's from the original mod or the fork but at least my modpack that I'm making is the one with a red circle but every time I create a machine with /cm create it creates a new instance instead of using where am I creating the modpack

![image](https://github.com/user-attachments/assets/cbcadf9b-02ee-4a5b-8105-3eb683768856)

new test (for now this stuff only happening in fork 1.20)
i create teste 1.20 and when i create machine mod create a new instance and save there (teste 1)

![image2](https://github.com/user-attachments/assets/b843c0a9-fbc4-4280-be5a-7d82d2af7273)

i create new modpack only with JEI and CM and try /cm create to create new machine

**Comment by arketec** [comment]
thanks for the report. I have fixed this specific issue in the latest beta release, however the client creation UI is still buggy so I recommend sticking to JSON files for now
